Started by user [8mha:////4KuUW7S9534PynVfBTj8ydAQcukQ195/ubXCuSPFkvQUAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0mAdmin
Running in Durability level: MAX_SURVIVABILITY
[8mha:////4JzQ5a3ORR2Aii60HhUv2ECZXltetXbVofeEZj1K3xcfAAAAoh+LCAAAAAAAAP9tjTEOwjAQBM8BClpKHuFItIiK1krDC0x8GCfWnbEdkooX8TX+gCESFVvtrLSa5wtWKcKBo5UdUu8otU4GP9jS5Mixv3geZcdn2TIl9igbHBs2eJyx4YwwR1SwULBGaj0nRzbDRnX6rmuvydanHMu2V1A5c4MHCFXMWcf8hSnC9jqYxPTz/BXAFEIGsfuclm8zQVqFvQAAAA==[0m[Pipeline] Start of Pipeline
[8mha:////4IdnChl9l6G4hXAEuShp/yQ6FaJhTRQQd4Kjmb6t5iwIAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycohUghExsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jduZBmjwAAAAA==[0m[Pipeline] node
Running on [8mha:////4FjOp36XCM+43LtkNjAPG5srO2QSver89qY/Jdhg3DjGAAAAnh+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAz2EgZh/eT83ILSktQifY3cxGIgrakPAHib2iPIAAAA[0mJenkins in /var/lib/jenkins/workspace/allbranchautomation_rev1
[8mha:////4Lkg7mM80WMHXPrSkIk+4SO5oo0mTqAWW4Ua17Zr/wwyAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gA0xsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jfoP95RwAAAAA==[0m[Pipeline] {
[8mha:////4BMrxdhhsDqXbtB9wRMYpdvQBS2qw0rISF8xI44Q2j2TAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0gQkxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jc09154wAAAAA==[0m[Pipeline] stage
[8mha:////4NNQQjz0poTPupLbCSK7mPJC+vC4UfEfzlWpIBya7r5tAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+KOrAycoh0ggUxsUZZOEFIQkgb/d8mKe3EibgadyBQiQlLlmxL1nu+oE4RjhQdby12HpP2vA+jK4lPFLtroIm3dOGaMFGwXNpJkrGnpUrKFhaxClYC1hZ1oOTRZdiIVt1VExS65pxj2Q4CKm8GeAAThZxVzN8yR9jeRpMIf5y/AJj7DGxXvP/86jek7ggRwAAAAA==[0m[Pipeline] { (Cleaning Workspace)
[8mha:////4MMggADd59MJAjPzyX5l895WgNVAlc4YchURqmyYPKYcAAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbaWGsbAmNJ0AWEZb8zwLrbuWJvJp3kLiJlZNMMm+a93rDOic4UbLcG+wdZu14DKOti0+U+lugiXu6ck2YKRguzSSpM+cFJRUDS1gDKwEbgzpQdmgLbIVXD9UGhba9lFS/o4DGdQM8gYlqLiqVL8wJdvexy4Q/z18BzLEA29ce4gfg7KmOvAAAAA==[0m[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[8mha:////4HJkqq3LsWx7+APtz8udDihIVeF332uGR+wzUBViQbK8AAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQTbGRNjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9Dg2gqvAAAAA==[0m[Pipeline] }
[8mha:////4GJ0N7sEfvL5WvnDaKLxuGtUe2cMtjfNIflfwDOPusD1AAAAoh+LCAAAAAAAAP9tjTEOAiEURD9rLGwtPQRbWRhjZUtoPAGyiLDkfxZYdytP5NW8g8RNrJxkknnTvNcb1jnBiZLl3mDvMGvHYxhtXXyi1N8CTdzTlWvCTMFwaSZJnTkvKKkYWMIaWAnYGNSBskNbYCu8eqg2KLTtpaT6HQU0rhvgCUxUc1GpfGFOsLuPXSb8ef4KYI6xADvU7j9J+wGOvAAAAA==[0m[Pipeline] // stage
[8mha:////4J5aWD8cYk4wxm9f1cvzbno8Q0Rm7ijt6bETRrIv5nUwAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQDEh2iorXc8AITG+PEugv2haTiRXyNPxCIRMVWOyut5vmCMic4UPKycdgGzHWQXez91ORAqb1EGmRDZ1kTZopOajdosu44oyZ2MEcUsFCwdFhHygE9w0o15m6qaNBXJ07TtldQBHuDBwg1mdkk/sKYYH3tbSb8ef4KYOwYxI6h2G4+x/INtuQqUcEAAAA=[0m[Pipeline] stage
[8mha:////4EBiGAlcyYGPal4u9lXjtPI45bdjP7Q3t/lxPUpr5fFSAAAApR+LCAAAAAAAAP9tjTEOwjAUQ3+DOrAycoiUzoiJNerCCUITQtLo/zZJSSdOxNW4Ay2VmPBg2Zas93pDGQOcKBjuNHYWY2t570czJ54pdDdPmTu68pYwkte80bkhpc9rbShpWFUw2AjYamw9RYsmwU44+ZCVl2iqSwrzdhTArBrgCYWYyUmG9C1TgP19VJHwx/kLgKlPwOrDYvXyLD8BobDcwgAAAA==[0m[Pipeline] { (Getting the repos list and clone them.)
[8mha:////4A55XhFp+XzR34ZTKuzLM5E8Jh8zumaFko1WYDtw2VRWAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggysXWsbBkaT4AJIoT5nwCRVJ7Iq3kH0cxYucXOvm3e8wXrGOBIQTOrcDAYO8O8m3RZLFMYro4ys3RhHWEkp5hQWVCvTgsKSgqWVDWsOGwUdo6iQZ1gy628y8ZJ1M05hfIdONSmH+EBFS/mJEP6whxgd5v6SPjz/BXA7BPUbfupvX8DpQJrNb4AAAA=[0m[Pipeline] sh
Cloning into 'final'...
Cloning into 'test001'...
Cloning into 'test002'...
Cloning into 'test003'...
Cloning into 'test004'...
Cloning into 'test005'...
Cloning into 'test006'...
Cloning into 'testing'...
Cloning into 'test001_fork'...
Cloning into '_fork'...
Cloning into 'test002_fork'...
Cloning into 'test003_fork'...
Cloning into 'test007'...
Cloning into 'test006_fork'...
Cloning into 'maven_test1'...
Cloning into 'test0001_forkengy'...
Cloning into 'forkes_test0001_engy'...
Cloning into 'forked-i'...
Cloning into 'forked-final'...
Cloning into 'forked-test001'...
Cloning into 'forked-test002'...
Cloning into 'forked-test003'...
Cloning into 'forked-test004'...
Cloning into 'forked-test005'...
Cloning into 'forked-test006'...
Cloning into 'forked-testing'...
Cloning into 'forked-test001_fork'...
Cloning into 'forked-_fork'...
Cloning into 'fork_repos_automation'...
Cloning into 'first'...
Cloning into 'dev'...
Cloning into 'testmultiimport'...
Cloning into 'grey-project-1'...
Cloning into 'grey-project-2'...
Cloning into 'grey-project-3'...
Cloning into 'grey-project-5'...
Cloning into 'grey-project-4'...
Cloning into 'slamr-project-1'...
Cloning into 'slamr-project-2'...
Cloning into 'forked_23-jun-grey-project-1'...
Cloning into 'forked_23-jun-grey-project-2'...
Cloning into 'forked_23-jun-grey-project-3'...
Cloning into 'forked_23-jun-grey-project-5'...
Cloning into 'forked_23-jun-grey-project-4'...
Cloning into 'forked_23-jun-forked_23-jun-grey-project-1'...
Cloning into 'forked_23-jun-forked_23-jun-grey-project-2'...
Cloning into 'forked_23-jun-forked_23-jun-grey-project-3'...
Cloning into 'forked_23-jun-forked_23-jun-grey-project-5'...
Cloning into 'forked_23-jun-forked_23-jun-grey-project-4'...
Cloning into 'forked_23-jun-slamr-project-1'...
Cloning into 'forked_23-jun-slamr-project-2'...
Cloning into 'forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1'...
Cloning into 'forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2'...
Cloning into 'forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3'...
Cloning into 'forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5'...
Cloning into 'forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4'...
Cloning into 'forked_23-jun-forked_23-jun-slamr-project-1'...
Cloning into 'forked_23-jun-forked_23-jun-slamr-project-2'...
Cloning into 'slamr_grey-project-1'...
Cloning into 'slamr_grey-project-2'...
Cloning into 'slamr_grey-project-3'...
Cloning into 'slamr_grey-project-5'...
Cloning into 'slamr_grey-project-4'...
Cloning into 'slamr_forked_23-jun-grey-project-1'...
Cloning into 'slamr_forked_23-jun-grey-project-2'...
Cloning into 'slamr_forked_23-jun-grey-project-3'...
Cloning into 'slamr_forked_23-jun-grey-project-5'...
Cloning into 'slamr_forked_23-jun-grey-project-4'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-grey-project-1'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-grey-project-2'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-grey-project-3'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-grey-project-5'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-grey-project-4'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5'...
Cloning into 'slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4'...
Cloning into 'greyspace1'...
Cloning into 'greyspace3'...
Cloning into 'greyspace4'...
Cloning into 'greyspace2'...
Cloning into 'slamr_greyspace1'...
Cloning into 'slamr_greyspace3'...
Cloning into 'slamr_greyspace4'...
Cloning into 'slamr_greyspace2'...
Cloning into 'slamr_greyspace5'...
Cloning into 'allbranchautomation'...
[8mha:////4PNMuYSitzv8iBEKxRyL4ETIHz+kADcvL3zJdO+j9jxzAAAAox+LCAAAAAAAAP9tjTESwiAURH/iWNhaeggyGUvHypah8QSYIEKY/wkQSeWJvJp3EM2MlVvs7NvmPV+wjgGOFDSzCgeDsTPMu0mXxTKF4eooM0sX1hFGcooJlQX16rSgoKRgSVXDisNGYecoGtQJttzKu2ycRN2cUyjfgUNt+hEeUPFiTjKkL8wBdrepj4Q/z18BzN4nqNv9p9o3geV5574AAAA=[0m[Pipeline] }
[8mha:////4F7JgnkuNFQBGh3CSVm23oxIxFj5OrWdyUnBKv8/J7eLAAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOICEh2iSmu54QUmNsaJdWdsh6TiRXyNPxCIRMUWq51t5vmCZYpw5GixNdQ5So3D4Hs7LRw4dhfPA7Z8xoYpsTcozSBZm3pGydnAnKKEhYCVocZzcmQzrEWr7qryimx1ynH6DgJKp2/wgEJM5qxi/sIYYXPtdWL6ef4KYAwhQ7nbf2r7Bq/le42+AAAA[0m[Pipeline] // stage
[8mha:////4MSudsnK5B/KY8AEqZH9srFl6Y0sd2tN7/ja/2nR0F7TAAAAph+LCAAAAAAAAP9tjTEOwjAQBM9BKWgpeYQjJKgQFa3lhheY2Bgn1l2wLyQVL+Jr/IFAJCq22llpNc8XlDnBgZKXjcM2YK6D7GLvpyYHSu0l0iAbOsuaMFN0UrtBk3XHGTWxgzmigIWCpcM6Ug7oGVaqMXdTRYO+OnGatr2CItgbPECoycwm8RfGBOtrbzPhz/NXAGPHILYMxWb3OZZvBXXnAcEAAAA=[0m[Pipeline] stage
[8mha:////4BvgUAB3sNyFJl8vHppORYQTH0sbe41AwhAHzPQeunVRAAAApx+LCAAAAAAAAP9tjTEOwjAUQ3+LOrAycohUDLAgpq5RFk4QmhDSRv+Xn5R24kRcjTvQUokJD5ZtyXqvNxSR4UTsRGOx9RhrL7rQuymJgbi9BhpEQxdRE0YKVig7KDK2WqqiZGFRlsNKwtpiHSh6dAk2stEPXQaNrjwnnrajhNybOzwhkxM5aU7fMjJsb72JhD/OXwCMXYJ8t5/tMD+LD/s94rDCAAAA[0m[Pipeline] { (automation)
[8mha:////4JDq0xetG3nxESBDZ95Qk/DpT2XaeynrvbcGyRLnAJi4AAAApB+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiGigQVVrLDS8wsTFOrDtjOyQVL+Jr/IFAJCq2WO1sM88XLFOEI0eLraHOUWocBt/baeHAsbt4HrDlMzZMib1BaQbJ2tQzSs4G5hQlLASsDDWekyObYS1adVeVV2SrU47TdxBQOn2DBxRiMmcV8xfGCJtrrxPTz/NXAGPIUG53n9qHN27Iu42+AAAA[0m[Pipeline] sh
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/final/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/final.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/final
 * branch            master     -> FETCH_HEAD
Everything up-to-date
To https://bitbucket.org/pietto/final.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/final
 * branch            develop    -> FETCH_HEAD
Everything up-to-date
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/test001: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test001/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test001.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/final
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/test001.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test001.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/test001.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/final
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/test001.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test001.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/test002: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test002/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test002.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/final
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/test002.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test002.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/test002.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/final
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/test002.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test002.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test003/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test003.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test003
 * branch            master     -> FETCH_HEAD
Everything up-to-date
To https://bitbucket.org/pietto/test003.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test003
 * branch            develop    -> FETCH_HEAD
Everything up-to-date
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/test004: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test004/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test004.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test003
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/test004.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test004.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/test004.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test003
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/test004.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test004.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test005/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test005.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test005
 * branch            master     -> FETCH_HEAD
   aa0ee04..295943b  master     -> origin/master
Everything up-to-date
To https://bitbucket.org/pietto/test005.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test005
 * branch            develop    -> FETCH_HEAD
   aa0ee04..295943b  develop    -> origin/develop
Everything up-to-date
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test006/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test006.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006
 * branch            master     -> FETCH_HEAD
   69b9ee1..9da292a  master     -> origin/master
Everything up-to-date
To https://bitbucket.org/pietto/test006.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006
 * branch            develop    -> FETCH_HEAD
   69b9ee1..9da292a  develop    -> origin/develop
Everything up-to-date
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/testing/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/testing.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/testing
 * branch            master     -> FETCH_HEAD
Everything up-to-date
To https://bitbucket.org/pietto/testing.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/testing
 * branch            develop    -> FETCH_HEAD
Everything up-to-date
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/test001_fork: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test001_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test001_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/testing
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/test001_fork.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test001_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/test001_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/testing
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/test001_fork.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/test001_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/_fork
 * branch            master     -> FETCH_HEAD
   10fcf91..e4a006c  master     -> origin/master
Everything up-to-date
To https://bitbucket.org/pietto/_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/_fork
 * branch            develop    -> FETCH_HEAD
   10fcf91..e4a006c  develop    -> origin/develop
Everything up-to-date
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test002_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test002_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test002_fork
 * branch            master     -> FETCH_HEAD
   2edae2d..a58deb1  master     -> origin/master
Everything up-to-date
To https://bitbucket.org/pietto/test002_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test002_fork
 * branch            develop    -> FETCH_HEAD
   2edae2d..a58deb1  develop    -> origin/develop
Everything up-to-date
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test003_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test003_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test003_fork
 * branch            master     -> FETCH_HEAD
   2e4f5c8..aeb0f9d  master     -> origin/master
Everything up-to-date
To https://bitbucket.org/pietto/test003_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test003_fork
 * branch            develop    -> FETCH_HEAD
   2e4f5c8..aeb0f9d  develop    -> origin/develop
Everything up-to-date
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test007/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test007.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test007
 * branch            master     -> FETCH_HEAD
   aa99afb..60c5475  master     -> origin/master
To https://bitbucket.org/pietto/test007.git
   60c5475..eb4f598  master -> master
To https://bitbucket.org/pietto/test007.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test007
 * branch            develop    -> FETCH_HEAD
   c82b8d4..60c5475  develop    -> origin/develop
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/test007/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/test007.git
   60c5475..eb4f598  develop -> develop
Switched to a new branch 'release/3_2_0'
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test006_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test006_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/test006_fork.git
   f0b611f..1643017  master -> master
To https://bitbucket.org/pietto/test006_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/test006_fork/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/test006_fork.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/maven_test1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/maven_test1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/maven_test1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
   f0b611f..1643017  master     -> origin/master
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/maven_test1/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/maven_test1.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/maven_test1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
   f0b611f..1643017  develop    -> origin/develop
To https://bitbucket.org/pietto/maven_test1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/test0001_forkengy: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/test0001_forkengy/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/test0001_forkengy.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/test0001_forkengy/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/test0001_forkengy.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/test0001_forkengy.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/test0001_forkengy.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forkes_test0001_engy: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forkes_test0001_engy/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forkes_test0001_engy.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forkes_test0001_engy.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forkes_test0001_engy.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forkes_test0001_engy.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forkes_test0001_engy.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forkes_test0001_engy.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-i: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-i/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked-i.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-i.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-i.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-i.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-i.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-i.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-final: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-final/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked-final.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-final.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-final.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-final.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-final.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-final.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test001: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test001/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test001.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test001.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test001.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test001.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test001.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test001.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test002: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test002/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test002.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test002.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test002.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test002.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test002.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test002.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test003: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test003/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test003.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test003.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test003.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test003.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test003.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test003.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test004: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test004/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test004.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test004.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test004.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test004.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test004.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test004.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test005: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test005/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test005.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test005.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test005.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test005.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test005.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test005.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test006: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test006/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-test006.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test006.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test006.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test006.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test006.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test006.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-testing: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-testing/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/forked-testing.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-testing.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-testing.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-testing.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-testing.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-testing.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-test001_fork: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-test001_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked-test001_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test001_fork.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test001_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-test001_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-test001_fork.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-test001_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked-_fork: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked-_fork/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked-_fork.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-_fork.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked-_fork.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked-_fork.git
 ! [rejected]        develop -> develop (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked-_fork.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/fork_repos_automation: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/fork_repos_automation/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/fork_repos_automation.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/fork_repos_automation.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/fork_repos_automation.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/fork_repos_automation.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/fork_repos_automation/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/fork_repos_automation.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/first: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/first/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/first.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/first.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/first.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/first.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/first/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/first.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/dev: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/dev/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/dev.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/dev/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/dev.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/dev.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/dev.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/testmultiimport: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/testmultiimport/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/testmultiimport.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/testmultiimport/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/testmultiimport.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/testmultiimport.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/testmultiimport.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/grey-project-1/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/grey-project-2/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/grey-project-3/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/grey-project-5/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/grey-project-4/pull-requests/new?source=release/3_2_0&t=1
remote: 
To https://bitbucket.org/pietto/grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr-project-2/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr-project-2.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1
remote: 
To https://bitbucket.org/pietto/forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-slamr-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-slamr-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-slamr-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-slamr-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-slamr-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-slamr-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/forked_23-jun-slamr-project-2/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-2.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-slamr-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-slamr-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/forked_23-jun-forked_23-jun-slamr-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/forked_23-jun-forked_23-jun-slamr-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_forked_23-jun-forked_23-jun-forked_23-jun-grey-project-4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/greyspace1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/greyspace1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/greyspace1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/greyspace1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/greyspace1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/greyspace1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/greyspace3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/greyspace3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/greyspace3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/greyspace3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/greyspace3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/greyspace3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/greyspace4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/greyspace4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/greyspace4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/greyspace4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/greyspace4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/greyspace2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/greyspace2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/greyspace2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/greyspace2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/greyspace2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/greyspace2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/greyspace2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_greyspace1: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_greyspace1/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace1.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_greyspace1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_greyspace1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_greyspace1.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_greyspace1/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace1.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_greyspace3: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_greyspace3/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace3.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_greyspace3.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_greyspace3.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_greyspace3.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_greyspace3/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace3.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_greyspace4: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_greyspace4/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace4.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_greyspace4/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace4.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_greyspace4.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_greyspace4.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_greyspace2: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_greyspace2/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace2.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_greyspace2.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/slamr_greyspace2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_greyspace2.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/slamr_greyspace2/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace2.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/slamr_greyspace5: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/slamr_greyspace5/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace5.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
remote: 
remote: Create pull request for master:        
remote:   https://bitbucket.org/pietto/slamr_greyspace5/pull-requests/new?source=master&t=1        
remote: 
To https://bitbucket.org/pietto/slamr_greyspace5.git
   f0b611f..1643017  master -> master
fatal: tag '20' already exists
To https://bitbucket.org/pietto/slamr_greyspace5.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
To https://bitbucket.org/pietto/slamr_greyspace5.git
   f0b611f..1643017  develop -> develop
/var/lib/jenkins/workspace/allbranchautomation_rev1@tmp/durable-f62dd611/script.sh: line 10: cd: /var/lib/jenkins/workspace/allbranchautomation/allbranchautomation: No such file or directory
fatal: A branch named 'release/3_2_0' already exists.
remote: 
remote: Create pull request for release/3_2_0:        
remote:   https://bitbucket.org/pietto/allbranchautomation/pull-requests/new?source=release/3_2_0&t=1        
remote: 
To https://bitbucket.org/pietto/allbranchautomation.git
 * [new branch]      release/3_2_0 -> release/3_2_0
Switched to branch 'master'
From https://bitbucket.org/pietto/test006_fork
 * branch            master     -> FETCH_HEAD
To https://bitbucket.org/pietto/allbranchautomation.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://pietto:Smooch!991@bitbucket.org/pietto/allbranchautomation.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
fatal: tag '20' already exists
To https://bitbucket.org/pietto/allbranchautomation.git
 * [new tag]         20 -> 20
Switched to branch 'develop'
From https://bitbucket.org/pietto/test006_fork
 * branch            develop    -> FETCH_HEAD
remote: 
remote: Create pull request for develop:        
remote:   https://bitbucket.org/pietto/allbranchautomation/pull-requests/new?source=develop&t=1        
remote: 
To https://bitbucket.org/pietto/allbranchautomation.git
   f0b611f..1643017  develop -> develop
[8mha:////4HmqsJ6ohOKV2jlfepwck53OeJYh3U5ZWY9G7IMHSt3pAAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiGoSEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQHhgNoTvgAAAA==[0m[Pipeline] }
[8mha:////4MM7OZzs5Ywg6peRDFJHBMWplo/9Zcn/m/4tX1QWK3z8AAAApR+LCAAAAAAAAP9tjTEOwjAQBC9BFLSUPOIiCgqEqNJabniBiY1xYt0Z2yGpeBFf4w8EIlGxxWpnm3m+YJkiHDlabA11jlLjMPjeTgsHjt3F84Atn7FhSuwNSjNI1qaeUXI2MKcoYSFgZajxnBzZDGvRqruqvCJbnXKcvoOA0ukbPKAQkzmrmL8wRthce52Yfp6/AhhDyFBu95/avQH+Ao9BvgAAAA==[0m[Pipeline] // stage
[8mha:////4PB3I03PAbr6YP0BJT+/JWFsljJ7yuQdKip99gyuMsKkAAAAox+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMJBiA5R0VppeIFJjHFi3QX7QlLxIr7GH4iIRMVWO9PM641lijhydKqx1HpKlVdd6N301MCxvQYeVMMXVTElDlaVdii5tqcZSxaLeVmOhcbKUhU4eXKCtW7MwxTBkCvOEid30Mh9fccTmZ7KYqJ8YYzY3Po6Mf06fwMYu06Q77aCbP8BK1nRVL0AAAA=[0m[Pipeline] }
[8mha:////4E9/h/G8iI4N5t89uGC9vyNJ6KjwVXOJoxDkgHALem4FAAAAoh+LCAAAAAAAAP9tjTEOwjAQBDdBFLSUPMIRUCIqWisNLzCJMU6su2BfSCpexNf4AxGRqNhqZ5p5vbFMEUeOTjWWWk+p8qoLvZueGji218CDaviiKqbEwarSDiXX9jRjyWIxL8ux0FhZqgInT06w1o15mCIYcsVZ4uQOGrmv73gi01NZTJQvjBGbW18npl/nbwBj1wny3VaQ7T845dX3vQAAAA==[0m[Pipeline] // node
[8mha:////4MNJ0Eb6TQKU+CqVdlUYc1rhsU21mstXQPXfd2Vt8QavAAAAoh+LCAAAAAAAAP9tjbEOgjAURS8YB1dHP6IkrMbJtWHxCyrUWmjeg/YhTH6Rv+Y/SCRx8k73nOW83timiBNHp1pLnadUe9WH0S1PTRy7W+BJtXxVNVPiYFVlp4obe16xYrFYl+XYaOws1YGTJyfY69Y8TBEMueIicXFHjdw3A57I9FIWE+ULc8ThPjaJ6df5G8Dc94K8LAVZ+QF+r3LHvQAAAA==[0m[Pipeline] End of Pipeline
Finished: SUCCESS
